# Exported from Render on 2024-10-22T15:23:07Z
services:
- type: web
  name: BE_BookingTicket
  runtime: node
  repo: https://github.com/hieunghiadev2002/BE_BookingTicket
  plan: free
  envVars:
  - key: EMAIL_PASS
    sync: false
  - key: EMAIL_USER
    sync: false
  - key: TWILIO_PHONE_NUMBER
    sync: false
  - key: TWILIO_AUTH_TOKEN
    sync: false
  - key: TWILIO_ACCOUNT_SID
    sync: false
  - key: ACCESS_TOKEN_SECRET
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: PORT
    sync: false
  - key: MONGODB_URL
    sync: false
  region: singapore
  buildCommand: npm install
  startCommand: npm start
  rootDir: src
version: "1"
